// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENTDATA_GWIPC_H_
#define FLATBUFFERS_GENERATED_CLIENTDATA_GWIPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 4,
             "Non-compatible flatbuffers version included");

namespace GWIPC {

struct Vec2;

struct Vec3;

struct Agent;

struct AgentLiving;
struct AgentLivingBuilder;

struct Skill;

struct Skillbar;
struct SkillbarBuilder;

struct Effect;

struct Buff;

struct Quest;
struct QuestBuilder;

struct Character;
struct CharacterBuilder;

struct Hero;
struct HeroBuilder;

struct MissionObjective;
struct MissionObjectiveBuilder;

struct Party;
struct PartyBuilder;

struct Instance;
struct InstanceBuilder;

struct Item;
struct ItemBuilder;

struct Bag;
struct BagBuilder;

struct GWDialog;
struct GWDialogBuilder;

struct DialogsInfo;
struct DialogsInfoBuilder;

struct AgentItem;
struct AgentItemBuilder;

struct AgentGadget;
struct AgentGadgetBuilder;

struct Enemy;
struct EnemyBuilder;

struct ClientData;
struct ClientDataBuilder;

enum MapInstanceType : int8_t {
  MapInstanceType_Outpost = 0,
  MapInstanceType_Explorable = 1,
  MapInstanceType_MIN = MapInstanceType_Outpost,
  MapInstanceType_MAX = MapInstanceType_Explorable
};

inline const MapInstanceType (&EnumValuesMapInstanceType())[2] {
  static const MapInstanceType values[] = {
    MapInstanceType_Outpost,
    MapInstanceType_Explorable
  };
  return values;
}

inline const char * const *EnumNamesMapInstanceType() {
  static const char * const names[3] = {
    "Outpost",
    "Explorable",
    nullptr
  };
  return names;
}

inline const char *EnumNameMapInstanceType(MapInstanceType e) {
  if (flatbuffers::IsOutRange(e, MapInstanceType_Outpost, MapInstanceType_Explorable)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMapInstanceType()[index];
}

enum GameState : int8_t {
  GameState_Unknown = 0,
  GameState_Loading = 1,
  GameState_CharSelect = 2,
  GameState_InGame = 3,
  GameState_MIN = GameState_Unknown,
  GameState_MAX = GameState_InGame
};

inline const GameState (&EnumValuesGameState())[4] {
  static const GameState values[] = {
    GameState_Unknown,
    GameState_Loading,
    GameState_CharSelect,
    GameState_InGame
  };
  return values;
}

inline const char * const *EnumNamesGameState() {
  static const char * const names[5] = {
    "Unknown",
    "Loading",
    "CharSelect",
    "InGame",
    nullptr
  };
  return names;
}

inline const char *EnumNameGameState(GameState e) {
  if (flatbuffers::IsOutRange(e, GameState_Unknown, GameState_InGame)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGameState()[index];
}

enum TeamColor : int8_t {
  TeamColor_None = 0,
  TeamColor_Blue = 1,
  TeamColor_Red = 2,
  TeamColor_Yellow = 3,
  TeamColor_MIN = TeamColor_None,
  TeamColor_MAX = TeamColor_Yellow
};

inline const TeamColor (&EnumValuesTeamColor())[4] {
  static const TeamColor values[] = {
    TeamColor_None,
    TeamColor_Blue,
    TeamColor_Red,
    TeamColor_Yellow
  };
  return values;
}

inline const char * const *EnumNamesTeamColor() {
  static const char * const names[5] = {
    "None",
    "Blue",
    "Red",
    "Yellow",
    nullptr
  };
  return names;
}

inline const char *EnumNameTeamColor(TeamColor e) {
  if (flatbuffers::IsOutRange(e, TeamColor_None, TeamColor_Yellow)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTeamColor()[index];
}

enum Profession : int8_t {
  Profession_None = 0,
  Profession_Warrior = 1,
  Profession_Ranger = 2,
  Profession_Monk = 3,
  Profession_Necromancer = 4,
  Profession_Mesmer = 5,
  Profession_Elementalist = 6,
  Profession_Assassin = 7,
  Profession_Ritualist = 8,
  Profession_Paragon = 9,
  Profession_Dervish = 10,
  Profession_MIN = Profession_None,
  Profession_MAX = Profession_Dervish
};

inline const Profession (&EnumValuesProfession())[11] {
  static const Profession values[] = {
    Profession_None,
    Profession_Warrior,
    Profession_Ranger,
    Profession_Monk,
    Profession_Necromancer,
    Profession_Mesmer,
    Profession_Elementalist,
    Profession_Assassin,
    Profession_Ritualist,
    Profession_Paragon,
    Profession_Dervish
  };
  return values;
}

inline const char * const *EnumNamesProfession() {
  static const char * const names[12] = {
    "None",
    "Warrior",
    "Ranger",
    "Monk",
    "Necromancer",
    "Mesmer",
    "Elementalist",
    "Assassin",
    "Ritualist",
    "Paragon",
    "Dervish",
    nullptr
  };
  return names;
}

inline const char *EnumNameProfession(Profession e) {
  if (flatbuffers::IsOutRange(e, Profession_None, Profession_Dervish)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProfession()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Agent FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t agent_id_;
  GWIPC::Vec3 position_;
  GWIPC::Vec3 terrain_normal_;
  float rotation_;
  GWIPC::Vec2 velocity_;
  float model_width_;
  float model_height_;
  uint32_t instance_timer_;

 public:
  Agent()
      : agent_id_(0),
        position_(),
        terrain_normal_(),
        rotation_(0),
        velocity_(),
        model_width_(0),
        model_height_(0),
        instance_timer_(0) {
  }
  Agent(uint32_t _agent_id, const GWIPC::Vec3 &_position, const GWIPC::Vec3 &_terrain_normal, float _rotation, const GWIPC::Vec2 &_velocity, float _model_width, float _model_height, uint32_t _instance_timer)
      : agent_id_(flatbuffers::EndianScalar(_agent_id)),
        position_(_position),
        terrain_normal_(_terrain_normal),
        rotation_(flatbuffers::EndianScalar(_rotation)),
        velocity_(_velocity),
        model_width_(flatbuffers::EndianScalar(_model_width)),
        model_height_(flatbuffers::EndianScalar(_model_height)),
        instance_timer_(flatbuffers::EndianScalar(_instance_timer)) {
  }
  uint32_t agent_id() const {
    return flatbuffers::EndianScalar(agent_id_);
  }
  const GWIPC::Vec3 &position() const {
    return position_;
  }
  const GWIPC::Vec3 &terrain_normal() const {
    return terrain_normal_;
  }
  float rotation() const {
    return flatbuffers::EndianScalar(rotation_);
  }
  const GWIPC::Vec2 &velocity() const {
    return velocity_;
  }
  float model_width() const {
    return flatbuffers::EndianScalar(model_width_);
  }
  float model_height() const {
    return flatbuffers::EndianScalar(model_height_);
  }
  uint32_t instance_timer() const {
    return flatbuffers::EndianScalar(instance_timer_);
  }
};
FLATBUFFERS_STRUCT_END(Agent, 52);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Skill FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t skill_id_;
  uint16_t recharge_ms_;
  uint8_t adrenaline_;
  int8_t padding0__;

 public:
  Skill()
      : skill_id_(0),
        recharge_ms_(0),
        adrenaline_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Skill(uint16_t _skill_id, uint16_t _recharge_ms, uint8_t _adrenaline)
      : skill_id_(flatbuffers::EndianScalar(_skill_id)),
        recharge_ms_(flatbuffers::EndianScalar(_recharge_ms)),
        adrenaline_(flatbuffers::EndianScalar(_adrenaline)),
        padding0__(0) {
    (void)padding0__;
  }
  uint16_t skill_id() const {
    return flatbuffers::EndianScalar(skill_id_);
  }
  uint16_t recharge_ms() const {
    return flatbuffers::EndianScalar(recharge_ms_);
  }
  uint8_t adrenaline() const {
    return flatbuffers::EndianScalar(adrenaline_);
  }
};
FLATBUFFERS_STRUCT_END(Skill, 6);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Effect FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t skill_id_;
  uint32_t source_agent_id_;
  float duration_;

 public:
  Effect()
      : skill_id_(0),
        source_agent_id_(0),
        duration_(0) {
  }
  Effect(uint32_t _skill_id, uint32_t _source_agent_id, float _duration)
      : skill_id_(flatbuffers::EndianScalar(_skill_id)),
        source_agent_id_(flatbuffers::EndianScalar(_source_agent_id)),
        duration_(flatbuffers::EndianScalar(_duration)) {
  }
  uint32_t skill_id() const {
    return flatbuffers::EndianScalar(skill_id_);
  }
  uint32_t source_agent_id() const {
    return flatbuffers::EndianScalar(source_agent_id_);
  }
  float duration() const {
    return flatbuffers::EndianScalar(duration_);
  }
};
FLATBUFFERS_STRUCT_END(Effect, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Buff FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t skill_id_;
  uint32_t target_agent_id_;
  uint32_t buff_id_;

 public:
  Buff()
      : skill_id_(0),
        target_agent_id_(0),
        buff_id_(0) {
  }
  Buff(uint32_t _skill_id, uint32_t _target_agent_id, uint32_t _buff_id)
      : skill_id_(flatbuffers::EndianScalar(_skill_id)),
        target_agent_id_(flatbuffers::EndianScalar(_target_agent_id)),
        buff_id_(flatbuffers::EndianScalar(_buff_id)) {
  }
  uint32_t skill_id() const {
    return flatbuffers::EndianScalar(skill_id_);
  }
  uint32_t target_agent_id() const {
    return flatbuffers::EndianScalar(target_agent_id_);
  }
  uint32_t buff_id() const {
    return flatbuffers::EndianScalar(buff_id_);
  }
};
FLATBUFFERS_STRUCT_END(Buff, 12);

struct AgentLiving FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AgentLivingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT = 4,
    VT_NAME = 6,
    VT_OWNER_AGENT_ID = 8,
    VT_ANIMATION_TYPE = 10,
    VT_WEAPON_ATTACK_SPEED = 12,
    VT_WEAPON_ATTACK_SPEED_MODIFIER = 14,
    VT_PLAYER_NUMBER = 16,
    VT_PRIMARY_PROFESSION = 18,
    VT_SECONDARY_PROFESSION = 20,
    VT_TEAM_COLOR = 22,
    VT_GUILD_ID = 24,
    VT_LEVEL = 26,
    VT_HEALTH = 28,
    VT_MAX_HEALTH = 30,
    VT_HEALTH_RECHARGE = 32,
    VT_ENERGY = 34,
    VT_MAX_ENERGY = 36,
    VT_ENERGY_RECHARGE = 38,
    VT_PARTY_SLOT = 40
  };
  const GWIPC::Agent *agent() const {
    return GetStruct<const GWIPC::Agent *>(VT_AGENT);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  uint32_t owner_agent_id() const {
    return GetField<uint32_t>(VT_OWNER_AGENT_ID, 0);
  }
  float animation_type() const {
    return GetField<float>(VT_ANIMATION_TYPE, 0.0f);
  }
  float weapon_attack_speed() const {
    return GetField<float>(VT_WEAPON_ATTACK_SPEED, 0.0f);
  }
  float weapon_attack_speed_modifier() const {
    return GetField<float>(VT_WEAPON_ATTACK_SPEED_MODIFIER, 0.0f);
  }
  uint16_t player_number() const {
    return GetField<uint16_t>(VT_PLAYER_NUMBER, 0);
  }
  GWIPC::Profession primary_profession() const {
    return static_cast<GWIPC::Profession>(GetField<int8_t>(VT_PRIMARY_PROFESSION, 0));
  }
  GWIPC::Profession secondary_profession() const {
    return static_cast<GWIPC::Profession>(GetField<int8_t>(VT_SECONDARY_PROFESSION, 0));
  }
  GWIPC::TeamColor team_color() const {
    return static_cast<GWIPC::TeamColor>(GetField<int8_t>(VT_TEAM_COLOR, 0));
  }
  uint16_t guild_id() const {
    return GetField<uint16_t>(VT_GUILD_ID, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  float health() const {
    return GetField<float>(VT_HEALTH, 0.0f);
  }
  uint32_t max_health() const {
    return GetField<uint32_t>(VT_MAX_HEALTH, 0);
  }
  float health_recharge() const {
    return GetField<float>(VT_HEALTH_RECHARGE, 0.0f);
  }
  float energy() const {
    return GetField<float>(VT_ENERGY, 0.0f);
  }
  uint32_t max_energy() const {
    return GetField<uint32_t>(VT_MAX_ENERGY, 0);
  }
  float energy_recharge() const {
    return GetField<float>(VT_ENERGY_RECHARGE, 0.0f);
  }
  uint8_t party_slot() const {
    return GetField<uint8_t>(VT_PARTY_SLOT, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<GWIPC::Agent>(verifier, VT_AGENT, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_OWNER_AGENT_ID, 4) &&
           VerifyField<float>(verifier, VT_ANIMATION_TYPE, 4) &&
           VerifyField<float>(verifier, VT_WEAPON_ATTACK_SPEED, 4) &&
           VerifyField<float>(verifier, VT_WEAPON_ATTACK_SPEED_MODIFIER, 4) &&
           VerifyField<uint16_t>(verifier, VT_PLAYER_NUMBER, 2) &&
           VerifyField<int8_t>(verifier, VT_PRIMARY_PROFESSION, 1) &&
           VerifyField<int8_t>(verifier, VT_SECONDARY_PROFESSION, 1) &&
           VerifyField<int8_t>(verifier, VT_TEAM_COLOR, 1) &&
           VerifyField<uint16_t>(verifier, VT_GUILD_ID, 2) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<float>(verifier, VT_HEALTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_HEALTH, 4) &&
           VerifyField<float>(verifier, VT_HEALTH_RECHARGE, 4) &&
           VerifyField<float>(verifier, VT_ENERGY, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_ENERGY, 4) &&
           VerifyField<float>(verifier, VT_ENERGY_RECHARGE, 4) &&
           VerifyField<uint8_t>(verifier, VT_PARTY_SLOT, 1) &&
           verifier.EndTable();
  }
};

struct AgentLivingBuilder {
  typedef AgentLiving Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent(const GWIPC::Agent *agent) {
    fbb_.AddStruct(AgentLiving::VT_AGENT, agent);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(AgentLiving::VT_NAME, name);
  }
  void add_owner_agent_id(uint32_t owner_agent_id) {
    fbb_.AddElement<uint32_t>(AgentLiving::VT_OWNER_AGENT_ID, owner_agent_id, 0);
  }
  void add_animation_type(float animation_type) {
    fbb_.AddElement<float>(AgentLiving::VT_ANIMATION_TYPE, animation_type, 0.0f);
  }
  void add_weapon_attack_speed(float weapon_attack_speed) {
    fbb_.AddElement<float>(AgentLiving::VT_WEAPON_ATTACK_SPEED, weapon_attack_speed, 0.0f);
  }
  void add_weapon_attack_speed_modifier(float weapon_attack_speed_modifier) {
    fbb_.AddElement<float>(AgentLiving::VT_WEAPON_ATTACK_SPEED_MODIFIER, weapon_attack_speed_modifier, 0.0f);
  }
  void add_player_number(uint16_t player_number) {
    fbb_.AddElement<uint16_t>(AgentLiving::VT_PLAYER_NUMBER, player_number, 0);
  }
  void add_primary_profession(GWIPC::Profession primary_profession) {
    fbb_.AddElement<int8_t>(AgentLiving::VT_PRIMARY_PROFESSION, static_cast<int8_t>(primary_profession), 0);
  }
  void add_secondary_profession(GWIPC::Profession secondary_profession) {
    fbb_.AddElement<int8_t>(AgentLiving::VT_SECONDARY_PROFESSION, static_cast<int8_t>(secondary_profession), 0);
  }
  void add_team_color(GWIPC::TeamColor team_color) {
    fbb_.AddElement<int8_t>(AgentLiving::VT_TEAM_COLOR, static_cast<int8_t>(team_color), 0);
  }
  void add_guild_id(uint16_t guild_id) {
    fbb_.AddElement<uint16_t>(AgentLiving::VT_GUILD_ID, guild_id, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(AgentLiving::VT_LEVEL, level, 0);
  }
  void add_health(float health) {
    fbb_.AddElement<float>(AgentLiving::VT_HEALTH, health, 0.0f);
  }
  void add_max_health(uint32_t max_health) {
    fbb_.AddElement<uint32_t>(AgentLiving::VT_MAX_HEALTH, max_health, 0);
  }
  void add_health_recharge(float health_recharge) {
    fbb_.AddElement<float>(AgentLiving::VT_HEALTH_RECHARGE, health_recharge, 0.0f);
  }
  void add_energy(float energy) {
    fbb_.AddElement<float>(AgentLiving::VT_ENERGY, energy, 0.0f);
  }
  void add_max_energy(uint32_t max_energy) {
    fbb_.AddElement<uint32_t>(AgentLiving::VT_MAX_ENERGY, max_energy, 0);
  }
  void add_energy_recharge(float energy_recharge) {
    fbb_.AddElement<float>(AgentLiving::VT_ENERGY_RECHARGE, energy_recharge, 0.0f);
  }
  void add_party_slot(uint8_t party_slot) {
    fbb_.AddElement<uint8_t>(AgentLiving::VT_PARTY_SLOT, party_slot, 0);
  }
  explicit AgentLivingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AgentLiving> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AgentLiving>(end);
    return o;
  }
};

inline flatbuffers::Offset<AgentLiving> CreateAgentLiving(
    flatbuffers::FlatBufferBuilder &_fbb,
    const GWIPC::Agent *agent = nullptr,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    uint32_t owner_agent_id = 0,
    float animation_type = 0.0f,
    float weapon_attack_speed = 0.0f,
    float weapon_attack_speed_modifier = 0.0f,
    uint16_t player_number = 0,
    GWIPC::Profession primary_profession = GWIPC::Profession_None,
    GWIPC::Profession secondary_profession = GWIPC::Profession_None,
    GWIPC::TeamColor team_color = GWIPC::TeamColor_None,
    uint16_t guild_id = 0,
    uint8_t level = 0,
    float health = 0.0f,
    uint32_t max_health = 0,
    float health_recharge = 0.0f,
    float energy = 0.0f,
    uint32_t max_energy = 0,
    float energy_recharge = 0.0f,
    uint8_t party_slot = 0) {
  AgentLivingBuilder builder_(_fbb);
  builder_.add_energy_recharge(energy_recharge);
  builder_.add_max_energy(max_energy);
  builder_.add_energy(energy);
  builder_.add_health_recharge(health_recharge);
  builder_.add_max_health(max_health);
  builder_.add_health(health);
  builder_.add_weapon_attack_speed_modifier(weapon_attack_speed_modifier);
  builder_.add_weapon_attack_speed(weapon_attack_speed);
  builder_.add_animation_type(animation_type);
  builder_.add_owner_agent_id(owner_agent_id);
  builder_.add_name(name);
  builder_.add_agent(agent);
  builder_.add_guild_id(guild_id);
  builder_.add_player_number(player_number);
  builder_.add_party_slot(party_slot);
  builder_.add_level(level);
  builder_.add_team_color(team_color);
  builder_.add_secondary_profession(secondary_profession);
  builder_.add_primary_profession(primary_profession);
  return builder_.Finish();
}

inline flatbuffers::Offset<AgentLiving> CreateAgentLivingDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const GWIPC::Agent *agent = nullptr,
    const char *name = nullptr,
    uint32_t owner_agent_id = 0,
    float animation_type = 0.0f,
    float weapon_attack_speed = 0.0f,
    float weapon_attack_speed_modifier = 0.0f,
    uint16_t player_number = 0,
    GWIPC::Profession primary_profession = GWIPC::Profession_None,
    GWIPC::Profession secondary_profession = GWIPC::Profession_None,
    GWIPC::TeamColor team_color = GWIPC::TeamColor_None,
    uint16_t guild_id = 0,
    uint8_t level = 0,
    float health = 0.0f,
    uint32_t max_health = 0,
    float health_recharge = 0.0f,
    float energy = 0.0f,
    uint32_t max_energy = 0,
    float energy_recharge = 0.0f,
    uint8_t party_slot = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GWIPC::CreateAgentLiving(
      _fbb,
      agent,
      name__,
      owner_agent_id,
      animation_type,
      weapon_attack_speed,
      weapon_attack_speed_modifier,
      player_number,
      primary_profession,
      secondary_profession,
      team_color,
      guild_id,
      level,
      health,
      max_health,
      health_recharge,
      energy,
      max_energy,
      energy_recharge,
      party_slot);
}

struct Skillbar FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SkillbarBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SKILLS = 4
  };
  const flatbuffers::Vector<const GWIPC::Skill *> *skills() const {
    return GetPointer<const flatbuffers::Vector<const GWIPC::Skill *> *>(VT_SKILLS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SKILLS) &&
           verifier.VerifyVector(skills()) &&
           verifier.EndTable();
  }
};

struct SkillbarBuilder {
  typedef Skillbar Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_skills(flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Skill *>> skills) {
    fbb_.AddOffset(Skillbar::VT_SKILLS, skills);
  }
  explicit SkillbarBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Skillbar> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Skillbar>(end);
    return o;
  }
};

inline flatbuffers::Offset<Skillbar> CreateSkillbar(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Skill *>> skills = 0) {
  SkillbarBuilder builder_(_fbb);
  builder_.add_skills(skills);
  return builder_.Finish();
}

inline flatbuffers::Offset<Skillbar> CreateSkillbarDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<GWIPC::Skill> *skills = nullptr) {
  auto skills__ = skills ? _fbb.CreateVectorOfStructs<GWIPC::Skill>(*skills) : 0;
  return GWIPC::CreateSkillbar(
      _fbb,
      skills__);
}

struct Quest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef QuestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4,
    VT_LOG_STATE = 6,
    VT_LOCATION = 8,
    VT_NAME = 10,
    VT_NPC_NAME = 12,
    VT_MAP_FROM = 14,
    VT_MAP_TO = 16,
    VT_MARKER = 18,
    VT_DESCRIPTION = 20,
    VT_OBJECTIVES = 22
  };
  uint32_t quest_id() const {
    return GetField<uint32_t>(VT_QUEST_ID, 0);
  }
  uint32_t log_state() const {
    return GetField<uint32_t>(VT_LOG_STATE, 0);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *npc_name() const {
    return GetPointer<const flatbuffers::String *>(VT_NPC_NAME);
  }
  uint32_t map_from() const {
    return GetField<uint32_t>(VT_MAP_FROM, 0);
  }
  uint32_t map_to() const {
    return GetField<uint32_t>(VT_MAP_TO, 0);
  }
  const GWIPC::Vec3 *marker() const {
    return GetStruct<const GWIPC::Vec3 *>(VT_MARKER);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  const flatbuffers::String *objectives() const {
    return GetPointer<const flatbuffers::String *>(VT_OBJECTIVES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_QUEST_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_LOG_STATE, 4) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_NPC_NAME) &&
           verifier.VerifyString(npc_name()) &&
           VerifyField<uint32_t>(verifier, VT_MAP_FROM, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAP_TO, 4) &&
           VerifyField<GWIPC::Vec3>(verifier, VT_MARKER, 4) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_OBJECTIVES) &&
           verifier.VerifyString(objectives()) &&
           verifier.EndTable();
  }
};

struct QuestBuilder {
  typedef Quest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_quest_id(uint32_t quest_id) {
    fbb_.AddElement<uint32_t>(Quest::VT_QUEST_ID, quest_id, 0);
  }
  void add_log_state(uint32_t log_state) {
    fbb_.AddElement<uint32_t>(Quest::VT_LOG_STATE, log_state, 0);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(Quest::VT_LOCATION, location);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Quest::VT_NAME, name);
  }
  void add_npc_name(flatbuffers::Offset<flatbuffers::String> npc_name) {
    fbb_.AddOffset(Quest::VT_NPC_NAME, npc_name);
  }
  void add_map_from(uint32_t map_from) {
    fbb_.AddElement<uint32_t>(Quest::VT_MAP_FROM, map_from, 0);
  }
  void add_map_to(uint32_t map_to) {
    fbb_.AddElement<uint32_t>(Quest::VT_MAP_TO, map_to, 0);
  }
  void add_marker(const GWIPC::Vec3 *marker) {
    fbb_.AddStruct(Quest::VT_MARKER, marker);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(Quest::VT_DESCRIPTION, description);
  }
  void add_objectives(flatbuffers::Offset<flatbuffers::String> objectives) {
    fbb_.AddOffset(Quest::VT_OBJECTIVES, objectives);
  }
  explicit QuestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Quest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Quest>(end);
    return o;
  }
};

inline flatbuffers::Offset<Quest> CreateQuest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t quest_id = 0,
    uint32_t log_state = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> npc_name = 0,
    uint32_t map_from = 0,
    uint32_t map_to = 0,
    const GWIPC::Vec3 *marker = nullptr,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    flatbuffers::Offset<flatbuffers::String> objectives = 0) {
  QuestBuilder builder_(_fbb);
  builder_.add_objectives(objectives);
  builder_.add_description(description);
  builder_.add_marker(marker);
  builder_.add_map_to(map_to);
  builder_.add_map_from(map_from);
  builder_.add_npc_name(npc_name);
  builder_.add_name(name);
  builder_.add_location(location);
  builder_.add_log_state(log_state);
  builder_.add_quest_id(quest_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Quest> CreateQuestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t quest_id = 0,
    uint32_t log_state = 0,
    const char *location = nullptr,
    const char *name = nullptr,
    const char *npc_name = nullptr,
    uint32_t map_from = 0,
    uint32_t map_to = 0,
    const GWIPC::Vec3 *marker = nullptr,
    const char *description = nullptr,
    const char *objectives = nullptr) {
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto npc_name__ = npc_name ? _fbb.CreateString(npc_name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto objectives__ = objectives ? _fbb.CreateString(objectives) : 0;
  return GWIPC::CreateQuest(
      _fbb,
      quest_id,
      log_state,
      location__,
      name__,
      npc_name__,
      map_from,
      map_to,
      marker,
      description__,
      objectives__);
}

struct Character FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CharacterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT_LIVING = 4,
    VT_SKILLBAR = 6,
    VT_EFFECTS = 8,
    VT_BUFFS = 10,
    VT_TARGET_AGENT_ID = 12
  };
  const GWIPC::AgentLiving *agent_living() const {
    return GetPointer<const GWIPC::AgentLiving *>(VT_AGENT_LIVING);
  }
  const GWIPC::Skillbar *skillbar() const {
    return GetPointer<const GWIPC::Skillbar *>(VT_SKILLBAR);
  }
  const flatbuffers::Vector<const GWIPC::Effect *> *effects() const {
    return GetPointer<const flatbuffers::Vector<const GWIPC::Effect *> *>(VT_EFFECTS);
  }
  const flatbuffers::Vector<const GWIPC::Buff *> *buffs() const {
    return GetPointer<const flatbuffers::Vector<const GWIPC::Buff *> *>(VT_BUFFS);
  }
  uint32_t target_agent_id() const {
    return GetField<uint32_t>(VT_TARGET_AGENT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_AGENT_LIVING) &&
           verifier.VerifyTable(agent_living()) &&
           VerifyOffset(verifier, VT_SKILLBAR) &&
           verifier.VerifyTable(skillbar()) &&
           VerifyOffset(verifier, VT_EFFECTS) &&
           verifier.VerifyVector(effects()) &&
           VerifyOffset(verifier, VT_BUFFS) &&
           verifier.VerifyVector(buffs()) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_AGENT_ID, 4) &&
           verifier.EndTable();
  }
};

struct CharacterBuilder {
  typedef Character Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent_living(flatbuffers::Offset<GWIPC::AgentLiving> agent_living) {
    fbb_.AddOffset(Character::VT_AGENT_LIVING, agent_living);
  }
  void add_skillbar(flatbuffers::Offset<GWIPC::Skillbar> skillbar) {
    fbb_.AddOffset(Character::VT_SKILLBAR, skillbar);
  }
  void add_effects(flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Effect *>> effects) {
    fbb_.AddOffset(Character::VT_EFFECTS, effects);
  }
  void add_buffs(flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Buff *>> buffs) {
    fbb_.AddOffset(Character::VT_BUFFS, buffs);
  }
  void add_target_agent_id(uint32_t target_agent_id) {
    fbb_.AddElement<uint32_t>(Character::VT_TARGET_AGENT_ID, target_agent_id, 0);
  }
  explicit CharacterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Character> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Character>(end);
    return o;
  }
};

inline flatbuffers::Offset<Character> CreateCharacter(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::AgentLiving> agent_living = 0,
    flatbuffers::Offset<GWIPC::Skillbar> skillbar = 0,
    flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Effect *>> effects = 0,
    flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Buff *>> buffs = 0,
    uint32_t target_agent_id = 0) {
  CharacterBuilder builder_(_fbb);
  builder_.add_target_agent_id(target_agent_id);
  builder_.add_buffs(buffs);
  builder_.add_effects(effects);
  builder_.add_skillbar(skillbar);
  builder_.add_agent_living(agent_living);
  return builder_.Finish();
}

inline flatbuffers::Offset<Character> CreateCharacterDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::AgentLiving> agent_living = 0,
    flatbuffers::Offset<GWIPC::Skillbar> skillbar = 0,
    const std::vector<GWIPC::Effect> *effects = nullptr,
    const std::vector<GWIPC::Buff> *buffs = nullptr,
    uint32_t target_agent_id = 0) {
  auto effects__ = effects ? _fbb.CreateVectorOfStructs<GWIPC::Effect>(*effects) : 0;
  auto buffs__ = buffs ? _fbb.CreateVectorOfStructs<GWIPC::Buff>(*buffs) : 0;
  return GWIPC::CreateCharacter(
      _fbb,
      agent_living,
      skillbar,
      effects__,
      buffs__,
      target_agent_id);
}

struct Hero FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef HeroBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT_LIVING = 4,
    VT_SKILLBAR = 6,
    VT_EFFECTS = 8,
    VT_BUFFS = 10,
    VT_FLAG_POSITION = 12,
    VT_HERO_ID = 14,
    VT_OWNER_PLAYER_ID = 16
  };
  const GWIPC::AgentLiving *agent_living() const {
    return GetPointer<const GWIPC::AgentLiving *>(VT_AGENT_LIVING);
  }
  const GWIPC::Skillbar *skillbar() const {
    return GetPointer<const GWIPC::Skillbar *>(VT_SKILLBAR);
  }
  const flatbuffers::Vector<const GWIPC::Effect *> *effects() const {
    return GetPointer<const flatbuffers::Vector<const GWIPC::Effect *> *>(VT_EFFECTS);
  }
  const flatbuffers::Vector<const GWIPC::Buff *> *buffs() const {
    return GetPointer<const flatbuffers::Vector<const GWIPC::Buff *> *>(VT_BUFFS);
  }
  const GWIPC::Vec2 *flag_position() const {
    return GetStruct<const GWIPC::Vec2 *>(VT_FLAG_POSITION);
  }
  uint32_t hero_id() const {
    return GetField<uint32_t>(VT_HERO_ID, 0);
  }
  uint32_t owner_player_id() const {
    return GetField<uint32_t>(VT_OWNER_PLAYER_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_AGENT_LIVING) &&
           verifier.VerifyTable(agent_living()) &&
           VerifyOffset(verifier, VT_SKILLBAR) &&
           verifier.VerifyTable(skillbar()) &&
           VerifyOffset(verifier, VT_EFFECTS) &&
           verifier.VerifyVector(effects()) &&
           VerifyOffset(verifier, VT_BUFFS) &&
           verifier.VerifyVector(buffs()) &&
           VerifyField<GWIPC::Vec2>(verifier, VT_FLAG_POSITION, 4) &&
           VerifyField<uint32_t>(verifier, VT_HERO_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_OWNER_PLAYER_ID, 4) &&
           verifier.EndTable();
  }
};

struct HeroBuilder {
  typedef Hero Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent_living(flatbuffers::Offset<GWIPC::AgentLiving> agent_living) {
    fbb_.AddOffset(Hero::VT_AGENT_LIVING, agent_living);
  }
  void add_skillbar(flatbuffers::Offset<GWIPC::Skillbar> skillbar) {
    fbb_.AddOffset(Hero::VT_SKILLBAR, skillbar);
  }
  void add_effects(flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Effect *>> effects) {
    fbb_.AddOffset(Hero::VT_EFFECTS, effects);
  }
  void add_buffs(flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Buff *>> buffs) {
    fbb_.AddOffset(Hero::VT_BUFFS, buffs);
  }
  void add_flag_position(const GWIPC::Vec2 *flag_position) {
    fbb_.AddStruct(Hero::VT_FLAG_POSITION, flag_position);
  }
  void add_hero_id(uint32_t hero_id) {
    fbb_.AddElement<uint32_t>(Hero::VT_HERO_ID, hero_id, 0);
  }
  void add_owner_player_id(uint32_t owner_player_id) {
    fbb_.AddElement<uint32_t>(Hero::VT_OWNER_PLAYER_ID, owner_player_id, 0);
  }
  explicit HeroBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Hero> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Hero>(end);
    return o;
  }
};

inline flatbuffers::Offset<Hero> CreateHero(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::AgentLiving> agent_living = 0,
    flatbuffers::Offset<GWIPC::Skillbar> skillbar = 0,
    flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Effect *>> effects = 0,
    flatbuffers::Offset<flatbuffers::Vector<const GWIPC::Buff *>> buffs = 0,
    const GWIPC::Vec2 *flag_position = nullptr,
    uint32_t hero_id = 0,
    uint32_t owner_player_id = 0) {
  HeroBuilder builder_(_fbb);
  builder_.add_owner_player_id(owner_player_id);
  builder_.add_hero_id(hero_id);
  builder_.add_flag_position(flag_position);
  builder_.add_buffs(buffs);
  builder_.add_effects(effects);
  builder_.add_skillbar(skillbar);
  builder_.add_agent_living(agent_living);
  return builder_.Finish();
}

inline flatbuffers::Offset<Hero> CreateHeroDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::AgentLiving> agent_living = 0,
    flatbuffers::Offset<GWIPC::Skillbar> skillbar = 0,
    const std::vector<GWIPC::Effect> *effects = nullptr,
    const std::vector<GWIPC::Buff> *buffs = nullptr,
    const GWIPC::Vec2 *flag_position = nullptr,
    uint32_t hero_id = 0,
    uint32_t owner_player_id = 0) {
  auto effects__ = effects ? _fbb.CreateVectorOfStructs<GWIPC::Effect>(*effects) : 0;
  auto buffs__ = buffs ? _fbb.CreateVectorOfStructs<GWIPC::Buff>(*buffs) : 0;
  return GWIPC::CreateHero(
      _fbb,
      agent_living,
      skillbar,
      effects__,
      buffs__,
      flag_position,
      hero_id,
      owner_player_id);
}

struct MissionObjective FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MissionObjectiveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECTIVE_ID = 4,
    VT_DESCRIPTION = 6,
    VT_TYPE = 8
  };
  uint32_t objective_id() const {
    return GetField<uint32_t>(VT_OBJECTIVE_ID, 0);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  uint32_t type() const {
    return GetField<uint32_t>(VT_TYPE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJECTIVE_ID, 4) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint32_t>(verifier, VT_TYPE, 4) &&
           verifier.EndTable();
  }
};

struct MissionObjectiveBuilder {
  typedef MissionObjective Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_objective_id(uint32_t objective_id) {
    fbb_.AddElement<uint32_t>(MissionObjective::VT_OBJECTIVE_ID, objective_id, 0);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(MissionObjective::VT_DESCRIPTION, description);
  }
  void add_type(uint32_t type) {
    fbb_.AddElement<uint32_t>(MissionObjective::VT_TYPE, type, 0);
  }
  explicit MissionObjectiveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MissionObjective> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MissionObjective>(end);
    return o;
  }
};

inline flatbuffers::Offset<MissionObjective> CreateMissionObjective(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t objective_id = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    uint32_t type = 0) {
  MissionObjectiveBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_description(description);
  builder_.add_objective_id(objective_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<MissionObjective> CreateMissionObjectiveDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t objective_id = 0,
    const char *description = nullptr,
    uint32_t type = 0) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return GWIPC::CreateMissionObjective(
      _fbb,
      objective_id,
      description__,
      type);
}

struct Party FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PartyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTY_ID = 4,
    VT_PLAYER_MEMBERS = 6,
    VT_HERO_MEMBERS = 8,
    VT_HENCHMAN_MEMBERS = 10,
    VT_EXTRA_NPC_MEMBERS = 12,
    VT_FLAG_ALL_POSITION = 14,
    VT_MISSION_OBJECTIVES = 16
  };
  uint32_t party_id() const {
    return GetField<uint32_t>(VT_PARTY_ID, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *player_members() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *>(VT_PLAYER_MEMBERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Hero>> *hero_members() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Hero>> *>(VT_HERO_MEMBERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *henchman_members() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *>(VT_HENCHMAN_MEMBERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *extra_npc_members() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>> *>(VT_EXTRA_NPC_MEMBERS);
  }
  const GWIPC::Vec3 *flag_all_position() const {
    return GetStruct<const GWIPC::Vec3 *>(VT_FLAG_ALL_POSITION);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::MissionObjective>> *mission_objectives() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::MissionObjective>> *>(VT_MISSION_OBJECTIVES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PARTY_ID, 4) &&
           VerifyOffset(verifier, VT_PLAYER_MEMBERS) &&
           verifier.VerifyVector(player_members()) &&
           verifier.VerifyVectorOfTables(player_members()) &&
           VerifyOffset(verifier, VT_HERO_MEMBERS) &&
           verifier.VerifyVector(hero_members()) &&
           verifier.VerifyVectorOfTables(hero_members()) &&
           VerifyOffset(verifier, VT_HENCHMAN_MEMBERS) &&
           verifier.VerifyVector(henchman_members()) &&
           verifier.VerifyVectorOfTables(henchman_members()) &&
           VerifyOffset(verifier, VT_EXTRA_NPC_MEMBERS) &&
           verifier.VerifyVector(extra_npc_members()) &&
           verifier.VerifyVectorOfTables(extra_npc_members()) &&
           VerifyField<GWIPC::Vec3>(verifier, VT_FLAG_ALL_POSITION, 4) &&
           VerifyOffset(verifier, VT_MISSION_OBJECTIVES) &&
           verifier.VerifyVector(mission_objectives()) &&
           verifier.VerifyVectorOfTables(mission_objectives()) &&
           verifier.EndTable();
  }
};

struct PartyBuilder {
  typedef Party Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_party_id(uint32_t party_id) {
    fbb_.AddElement<uint32_t>(Party::VT_PARTY_ID, party_id, 0);
  }
  void add_player_members(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> player_members) {
    fbb_.AddOffset(Party::VT_PLAYER_MEMBERS, player_members);
  }
  void add_hero_members(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Hero>>> hero_members) {
    fbb_.AddOffset(Party::VT_HERO_MEMBERS, hero_members);
  }
  void add_henchman_members(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> henchman_members) {
    fbb_.AddOffset(Party::VT_HENCHMAN_MEMBERS, henchman_members);
  }
  void add_extra_npc_members(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> extra_npc_members) {
    fbb_.AddOffset(Party::VT_EXTRA_NPC_MEMBERS, extra_npc_members);
  }
  void add_flag_all_position(const GWIPC::Vec3 *flag_all_position) {
    fbb_.AddStruct(Party::VT_FLAG_ALL_POSITION, flag_all_position);
  }
  void add_mission_objectives(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::MissionObjective>>> mission_objectives) {
    fbb_.AddOffset(Party::VT_MISSION_OBJECTIVES, mission_objectives);
  }
  explicit PartyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Party> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Party>(end);
    return o;
  }
};

inline flatbuffers::Offset<Party> CreateParty(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t party_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> player_members = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Hero>>> hero_members = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> henchman_members = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentLiving>>> extra_npc_members = 0,
    const GWIPC::Vec3 *flag_all_position = nullptr,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::MissionObjective>>> mission_objectives = 0) {
  PartyBuilder builder_(_fbb);
  builder_.add_mission_objectives(mission_objectives);
  builder_.add_flag_all_position(flag_all_position);
  builder_.add_extra_npc_members(extra_npc_members);
  builder_.add_henchman_members(henchman_members);
  builder_.add_hero_members(hero_members);
  builder_.add_player_members(player_members);
  builder_.add_party_id(party_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Party> CreatePartyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t party_id = 0,
    const std::vector<flatbuffers::Offset<GWIPC::AgentLiving>> *player_members = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::Hero>> *hero_members = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::AgentLiving>> *henchman_members = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::AgentLiving>> *extra_npc_members = nullptr,
    const GWIPC::Vec3 *flag_all_position = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::MissionObjective>> *mission_objectives = nullptr) {
  auto player_members__ = player_members ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::AgentLiving>>(*player_members) : 0;
  auto hero_members__ = hero_members ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Hero>>(*hero_members) : 0;
  auto henchman_members__ = henchman_members ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::AgentLiving>>(*henchman_members) : 0;
  auto extra_npc_members__ = extra_npc_members ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::AgentLiving>>(*extra_npc_members) : 0;
  auto mission_objectives__ = mission_objectives ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::MissionObjective>>(*mission_objectives) : 0;
  return GWIPC::CreateParty(
      _fbb,
      party_id,
      player_members__,
      hero_members__,
      henchman_members__,
      extra_npc_members__,
      flag_all_position,
      mission_objectives__);
}

struct Instance FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InstanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INSTANCE_ID = 4,
    VT_MAP_ID = 6,
    VT_FILE_HASH = 8,
    VT_MAP_INSTANCE_TYPE = 10
  };
  uint32_t instance_id() const {
    return GetField<uint32_t>(VT_INSTANCE_ID, 0);
  }
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  uint32_t file_hash() const {
    return GetField<uint32_t>(VT_FILE_HASH, 0);
  }
  GWIPC::MapInstanceType map_instance_type() const {
    return static_cast<GWIPC::MapInstanceType>(GetField<int8_t>(VT_MAP_INSTANCE_TYPE, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INSTANCE_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_FILE_HASH, 4) &&
           VerifyField<int8_t>(verifier, VT_MAP_INSTANCE_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct InstanceBuilder {
  typedef Instance Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_instance_id(uint32_t instance_id) {
    fbb_.AddElement<uint32_t>(Instance::VT_INSTANCE_ID, instance_id, 0);
  }
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(Instance::VT_MAP_ID, map_id, 0);
  }
  void add_file_hash(uint32_t file_hash) {
    fbb_.AddElement<uint32_t>(Instance::VT_FILE_HASH, file_hash, 0);
  }
  void add_map_instance_type(GWIPC::MapInstanceType map_instance_type) {
    fbb_.AddElement<int8_t>(Instance::VT_MAP_INSTANCE_TYPE, static_cast<int8_t>(map_instance_type), 0);
  }
  explicit InstanceBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Instance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Instance>(end);
    return o;
  }
};

inline flatbuffers::Offset<Instance> CreateInstance(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t instance_id = 0,
    uint32_t map_id = 0,
    uint32_t file_hash = 0,
    GWIPC::MapInstanceType map_instance_type = GWIPC::MapInstanceType_Outpost) {
  InstanceBuilder builder_(_fbb);
  builder_.add_file_hash(file_hash);
  builder_.add_map_id(map_id);
  builder_.add_instance_id(instance_id);
  builder_.add_map_instance_type(map_instance_type);
  return builder_.Finish();
}

struct Item FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4,
    VT_NAME = 6,
    VT_SINGLE_ITEM_NAME = 8,
    VT_FULL_NAME = 10,
    VT_DESCRIPTION = 12,
    VT_MODEL_ID = 14,
    VT_ITEM_MODIFIER = 16,
    VT_INTERACTION = 18,
    VT_TYPE = 20,
    VT_VALUE = 22,
    VT_QUANTITY = 24,
    VT_IS_WEAPON_SET_ITEM = 26,
    VT_INDEX = 28
  };
  uint32_t item_id() const {
    return GetField<uint32_t>(VT_ITEM_ID, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *single_item_name() const {
    return GetPointer<const flatbuffers::String *>(VT_SINGLE_ITEM_NAME);
  }
  const flatbuffers::String *full_name() const {
    return GetPointer<const flatbuffers::String *>(VT_FULL_NAME);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  uint32_t model_id() const {
    return GetField<uint32_t>(VT_MODEL_ID, 0);
  }
  uint32_t item_modifier() const {
    return GetField<uint32_t>(VT_ITEM_MODIFIER, 0);
  }
  uint32_t interaction() const {
    return GetField<uint32_t>(VT_INTERACTION, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint16_t value() const {
    return GetField<uint16_t>(VT_VALUE, 0);
  }
  uint16_t quantity() const {
    return GetField<uint16_t>(VT_QUANTITY, 0);
  }
  bool is_weapon_set_item() const {
    return GetField<uint8_t>(VT_IS_WEAPON_SET_ITEM, 0) != 0;
  }
  uint8_t index() const {
    return GetField<uint8_t>(VT_INDEX, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ITEM_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_SINGLE_ITEM_NAME) &&
           verifier.VerifyString(single_item_name()) &&
           VerifyOffset(verifier, VT_FULL_NAME) &&
           verifier.VerifyString(full_name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint32_t>(verifier, VT_MODEL_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ITEM_MODIFIER, 4) &&
           VerifyField<uint32_t>(verifier, VT_INTERACTION, 4) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_VALUE, 2) &&
           VerifyField<uint16_t>(verifier, VT_QUANTITY, 2) &&
           VerifyField<uint8_t>(verifier, VT_IS_WEAPON_SET_ITEM, 1) &&
           VerifyField<uint8_t>(verifier, VT_INDEX, 1) &&
           verifier.EndTable();
  }
};

struct ItemBuilder {
  typedef Item Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_item_id(uint32_t item_id) {
    fbb_.AddElement<uint32_t>(Item::VT_ITEM_ID, item_id, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Item::VT_NAME, name);
  }
  void add_single_item_name(flatbuffers::Offset<flatbuffers::String> single_item_name) {
    fbb_.AddOffset(Item::VT_SINGLE_ITEM_NAME, single_item_name);
  }
  void add_full_name(flatbuffers::Offset<flatbuffers::String> full_name) {
    fbb_.AddOffset(Item::VT_FULL_NAME, full_name);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(Item::VT_DESCRIPTION, description);
  }
  void add_model_id(uint32_t model_id) {
    fbb_.AddElement<uint32_t>(Item::VT_MODEL_ID, model_id, 0);
  }
  void add_item_modifier(uint32_t item_modifier) {
    fbb_.AddElement<uint32_t>(Item::VT_ITEM_MODIFIER, item_modifier, 0);
  }
  void add_interaction(uint32_t interaction) {
    fbb_.AddElement<uint32_t>(Item::VT_INTERACTION, interaction, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(Item::VT_TYPE, type, 0);
  }
  void add_value(uint16_t value) {
    fbb_.AddElement<uint16_t>(Item::VT_VALUE, value, 0);
  }
  void add_quantity(uint16_t quantity) {
    fbb_.AddElement<uint16_t>(Item::VT_QUANTITY, quantity, 0);
  }
  void add_is_weapon_set_item(bool is_weapon_set_item) {
    fbb_.AddElement<uint8_t>(Item::VT_IS_WEAPON_SET_ITEM, static_cast<uint8_t>(is_weapon_set_item), 0);
  }
  void add_index(uint8_t index) {
    fbb_.AddElement<uint8_t>(Item::VT_INDEX, index, 0);
  }
  explicit ItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Item> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Item>(end);
    return o;
  }
};

inline flatbuffers::Offset<Item> CreateItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t item_id = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> single_item_name = 0,
    flatbuffers::Offset<flatbuffers::String> full_name = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    uint32_t model_id = 0,
    uint32_t item_modifier = 0,
    uint32_t interaction = 0,
    uint8_t type = 0,
    uint16_t value = 0,
    uint16_t quantity = 0,
    bool is_weapon_set_item = false,
    uint8_t index = 0) {
  ItemBuilder builder_(_fbb);
  builder_.add_interaction(interaction);
  builder_.add_item_modifier(item_modifier);
  builder_.add_model_id(model_id);
  builder_.add_description(description);
  builder_.add_full_name(full_name);
  builder_.add_single_item_name(single_item_name);
  builder_.add_name(name);
  builder_.add_item_id(item_id);
  builder_.add_quantity(quantity);
  builder_.add_value(value);
  builder_.add_index(index);
  builder_.add_is_weapon_set_item(is_weapon_set_item);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Item> CreateItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t item_id = 0,
    const char *name = nullptr,
    const char *single_item_name = nullptr,
    const char *full_name = nullptr,
    const char *description = nullptr,
    uint32_t model_id = 0,
    uint32_t item_modifier = 0,
    uint32_t interaction = 0,
    uint8_t type = 0,
    uint16_t value = 0,
    uint16_t quantity = 0,
    bool is_weapon_set_item = false,
    uint8_t index = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto single_item_name__ = single_item_name ? _fbb.CreateString(single_item_name) : 0;
  auto full_name__ = full_name ? _fbb.CreateString(full_name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return GWIPC::CreateItem(
      _fbb,
      item_id,
      name__,
      single_item_name__,
      full_name__,
      description__,
      model_id,
      item_modifier,
      interaction,
      type,
      value,
      quantity,
      is_weapon_set_item,
      index);
}

struct Bag FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BagBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BAG_SIZE = 4,
    VT_ITEMS = 6
  };
  uint8_t bag_size() const {
    return GetField<uint8_t>(VT_BAG_SIZE, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>> *items() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>> *>(VT_ITEMS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BAG_SIZE, 1) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
};

struct BagBuilder {
  typedef Bag Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_bag_size(uint8_t bag_size) {
    fbb_.AddElement<uint8_t>(Bag::VT_BAG_SIZE, bag_size, 0);
  }
  void add_items(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>>> items) {
    fbb_.AddOffset(Bag::VT_ITEMS, items);
  }
  explicit BagBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Bag> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Bag>(end);
    return o;
  }
};

inline flatbuffers::Offset<Bag> CreateBag(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t bag_size = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>>> items = 0) {
  BagBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_bag_size(bag_size);
  return builder_.Finish();
}

inline flatbuffers::Offset<Bag> CreateBagDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t bag_size = 0,
    const std::vector<flatbuffers::Offset<GWIPC::Item>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Item>>(*items) : 0;
  return GWIPC::CreateBag(
      _fbb,
      bag_size,
      items__);
}

struct GWDialog FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GWDialogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TEXT = 6,
    VT_SKILL_ID = 8,
    VT_BUTTON_ICON_ID = 10
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const flatbuffers::String *text() const {
    return GetPointer<const flatbuffers::String *>(VT_TEXT);
  }
  uint32_t skill_id() const {
    return GetField<uint32_t>(VT_SKILL_ID, 0);
  }
  uint32_t button_icon_id() const {
    return GetField<uint32_t>(VT_BUTTON_ICON_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           VerifyField<uint32_t>(verifier, VT_SKILL_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_BUTTON_ICON_ID, 4) &&
           verifier.EndTable();
  }
};

struct GWDialogBuilder {
  typedef GWDialog Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(GWDialog::VT_ID, id, 0);
  }
  void add_text(flatbuffers::Offset<flatbuffers::String> text) {
    fbb_.AddOffset(GWDialog::VT_TEXT, text);
  }
  void add_skill_id(uint32_t skill_id) {
    fbb_.AddElement<uint32_t>(GWDialog::VT_SKILL_ID, skill_id, 0);
  }
  void add_button_icon_id(uint32_t button_icon_id) {
    fbb_.AddElement<uint32_t>(GWDialog::VT_BUTTON_ICON_ID, button_icon_id, 0);
  }
  explicit GWDialogBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<GWDialog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GWDialog>(end);
    return o;
  }
};

inline flatbuffers::Offset<GWDialog> CreateGWDialog(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> text = 0,
    uint32_t skill_id = 0,
    uint32_t button_icon_id = 0) {
  GWDialogBuilder builder_(_fbb);
  builder_.add_button_icon_id(button_icon_id);
  builder_.add_skill_id(skill_id);
  builder_.add_text(text);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<GWDialog> CreateGWDialogDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *text = nullptr,
    uint32_t skill_id = 0,
    uint32_t button_icon_id = 0) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return GWIPC::CreateGWDialog(
      _fbb,
      id,
      text__,
      skill_id,
      button_icon_id);
}

struct DialogsInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DialogsInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIALOGS = 4,
    VT_LAST_DIALOG_ID = 6,
    VT_CURRENT_DIALOG_AGENT_ID = 8,
    VT_LAST_DIALOG_AGENT_ID = 10
  };
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::GWDialog>> *dialogs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::GWDialog>> *>(VT_DIALOGS);
  }
  uint32_t last_dialog_id() const {
    return GetField<uint32_t>(VT_LAST_DIALOG_ID, 0);
  }
  uint32_t current_dialog_agent_id() const {
    return GetField<uint32_t>(VT_CURRENT_DIALOG_AGENT_ID, 0);
  }
  uint32_t last_dialog_agent_id() const {
    return GetField<uint32_t>(VT_LAST_DIALOG_AGENT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIALOGS) &&
           verifier.VerifyVector(dialogs()) &&
           verifier.VerifyVectorOfTables(dialogs()) &&
           VerifyField<uint32_t>(verifier, VT_LAST_DIALOG_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_CURRENT_DIALOG_AGENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_LAST_DIALOG_AGENT_ID, 4) &&
           verifier.EndTable();
  }
};

struct DialogsInfoBuilder {
  typedef DialogsInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_dialogs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::GWDialog>>> dialogs) {
    fbb_.AddOffset(DialogsInfo::VT_DIALOGS, dialogs);
  }
  void add_last_dialog_id(uint32_t last_dialog_id) {
    fbb_.AddElement<uint32_t>(DialogsInfo::VT_LAST_DIALOG_ID, last_dialog_id, 0);
  }
  void add_current_dialog_agent_id(uint32_t current_dialog_agent_id) {
    fbb_.AddElement<uint32_t>(DialogsInfo::VT_CURRENT_DIALOG_AGENT_ID, current_dialog_agent_id, 0);
  }
  void add_last_dialog_agent_id(uint32_t last_dialog_agent_id) {
    fbb_.AddElement<uint32_t>(DialogsInfo::VT_LAST_DIALOG_AGENT_ID, last_dialog_agent_id, 0);
  }
  explicit DialogsInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<DialogsInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DialogsInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<DialogsInfo> CreateDialogsInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::GWDialog>>> dialogs = 0,
    uint32_t last_dialog_id = 0,
    uint32_t current_dialog_agent_id = 0,
    uint32_t last_dialog_agent_id = 0) {
  DialogsInfoBuilder builder_(_fbb);
  builder_.add_last_dialog_agent_id(last_dialog_agent_id);
  builder_.add_current_dialog_agent_id(current_dialog_agent_id);
  builder_.add_last_dialog_id(last_dialog_id);
  builder_.add_dialogs(dialogs);
  return builder_.Finish();
}

inline flatbuffers::Offset<DialogsInfo> CreateDialogsInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<GWIPC::GWDialog>> *dialogs = nullptr,
    uint32_t last_dialog_id = 0,
    uint32_t current_dialog_agent_id = 0,
    uint32_t last_dialog_agent_id = 0) {
  auto dialogs__ = dialogs ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::GWDialog>>(*dialogs) : 0;
  return GWIPC::CreateDialogsInfo(
      _fbb,
      dialogs__,
      last_dialog_id,
      current_dialog_agent_id,
      last_dialog_agent_id);
}

struct AgentItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AgentItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT = 4,
    VT_OWNER_AGENT_ID = 6,
    VT_EXTRA_TYPE = 8,
    VT_ITEM = 10
  };
  const GWIPC::Agent *agent() const {
    return GetStruct<const GWIPC::Agent *>(VT_AGENT);
  }
  uint32_t owner_agent_id() const {
    return GetField<uint32_t>(VT_OWNER_AGENT_ID, 0);
  }
  uint32_t extra_type() const {
    return GetField<uint32_t>(VT_EXTRA_TYPE, 0);
  }
  const GWIPC::Item *item() const {
    return GetPointer<const GWIPC::Item *>(VT_ITEM);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<GWIPC::Agent>(verifier, VT_AGENT, 4) &&
           VerifyField<uint32_t>(verifier, VT_OWNER_AGENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_EXTRA_TYPE, 4) &&
           VerifyOffset(verifier, VT_ITEM) &&
           verifier.VerifyTable(item()) &&
           verifier.EndTable();
  }
};

struct AgentItemBuilder {
  typedef AgentItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent(const GWIPC::Agent *agent) {
    fbb_.AddStruct(AgentItem::VT_AGENT, agent);
  }
  void add_owner_agent_id(uint32_t owner_agent_id) {
    fbb_.AddElement<uint32_t>(AgentItem::VT_OWNER_AGENT_ID, owner_agent_id, 0);
  }
  void add_extra_type(uint32_t extra_type) {
    fbb_.AddElement<uint32_t>(AgentItem::VT_EXTRA_TYPE, extra_type, 0);
  }
  void add_item(flatbuffers::Offset<GWIPC::Item> item) {
    fbb_.AddOffset(AgentItem::VT_ITEM, item);
  }
  explicit AgentItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AgentItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AgentItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<AgentItem> CreateAgentItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    const GWIPC::Agent *agent = nullptr,
    uint32_t owner_agent_id = 0,
    uint32_t extra_type = 0,
    flatbuffers::Offset<GWIPC::Item> item = 0) {
  AgentItemBuilder builder_(_fbb);
  builder_.add_item(item);
  builder_.add_extra_type(extra_type);
  builder_.add_owner_agent_id(owner_agent_id);
  builder_.add_agent(agent);
  return builder_.Finish();
}

struct AgentGadget FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AgentGadgetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT = 4,
    VT_NAME = 6,
    VT_EXTRA_TYPE = 8,
    VT_GADGET_ID = 10
  };
  const GWIPC::Agent *agent() const {
    return GetStruct<const GWIPC::Agent *>(VT_AGENT);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  uint32_t extra_type() const {
    return GetField<uint32_t>(VT_EXTRA_TYPE, 0);
  }
  uint32_t gadget_id() const {
    return GetField<uint32_t>(VT_GADGET_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<GWIPC::Agent>(verifier, VT_AGENT, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_EXTRA_TYPE, 4) &&
           VerifyField<uint32_t>(verifier, VT_GADGET_ID, 4) &&
           verifier.EndTable();
  }
};

struct AgentGadgetBuilder {
  typedef AgentGadget Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent(const GWIPC::Agent *agent) {
    fbb_.AddStruct(AgentGadget::VT_AGENT, agent);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(AgentGadget::VT_NAME, name);
  }
  void add_extra_type(uint32_t extra_type) {
    fbb_.AddElement<uint32_t>(AgentGadget::VT_EXTRA_TYPE, extra_type, 0);
  }
  void add_gadget_id(uint32_t gadget_id) {
    fbb_.AddElement<uint32_t>(AgentGadget::VT_GADGET_ID, gadget_id, 0);
  }
  explicit AgentGadgetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AgentGadget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AgentGadget>(end);
    return o;
  }
};

inline flatbuffers::Offset<AgentGadget> CreateAgentGadget(
    flatbuffers::FlatBufferBuilder &_fbb,
    const GWIPC::Agent *agent = nullptr,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    uint32_t extra_type = 0,
    uint32_t gadget_id = 0) {
  AgentGadgetBuilder builder_(_fbb);
  builder_.add_gadget_id(gadget_id);
  builder_.add_extra_type(extra_type);
  builder_.add_name(name);
  builder_.add_agent(agent);
  return builder_.Finish();
}

inline flatbuffers::Offset<AgentGadget> CreateAgentGadgetDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const GWIPC::Agent *agent = nullptr,
    const char *name = nullptr,
    uint32_t extra_type = 0,
    uint32_t gadget_id = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GWIPC::CreateAgentGadget(
      _fbb,
      agent,
      name__,
      extra_type,
      gadget_id);
}

struct Enemy FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EnemyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENT_LIVING = 4
  };
  const GWIPC::AgentLiving *agent_living() const {
    return GetPointer<const GWIPC::AgentLiving *>(VT_AGENT_LIVING);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_AGENT_LIVING) &&
           verifier.VerifyTable(agent_living()) &&
           verifier.EndTable();
  }
};

struct EnemyBuilder {
  typedef Enemy Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agent_living(flatbuffers::Offset<GWIPC::AgentLiving> agent_living) {
    fbb_.AddOffset(Enemy::VT_AGENT_LIVING, agent_living);
  }
  explicit EnemyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Enemy> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Enemy>(end);
    return o;
  }
};

inline flatbuffers::Offset<Enemy> CreateEnemy(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::AgentLiving> agent_living = 0) {
  EnemyBuilder builder_(_fbb);
  builder_.add_agent_living(agent_living);
  return builder_.Finish();
}

struct ClientData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ClientDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER = 4,
    VT_INSTANCE = 6,
    VT_PARTY = 8,
    VT_GAME_STATE = 10,
    VT_QUESTS = 12,
    VT_BAGS = 14,
    VT_ITEMS_EQUIPED = 16,
    VT_DIALOGS_INFO = 18,
    VT_NAV_MESH_FILE_PATH = 20,
    VT_ITEMS = 22,
    VT_GADGETS = 24,
    VT_ENEMIES = 26,
    VT_UNCLAIMED_ITEMS = 28,
    VT_MATERIAL_STORAGE = 30,
    VT_STORAGE = 32
  };
  const GWIPC::Character *character() const {
    return GetPointer<const GWIPC::Character *>(VT_CHARACTER);
  }
  const GWIPC::Instance *instance() const {
    return GetPointer<const GWIPC::Instance *>(VT_INSTANCE);
  }
  const GWIPC::Party *party() const {
    return GetPointer<const GWIPC::Party *>(VT_PARTY);
  }
  GWIPC::GameState game_state() const {
    return static_cast<GWIPC::GameState>(GetField<int8_t>(VT_GAME_STATE, 0));
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Quest>> *quests() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Quest>> *>(VT_QUESTS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>> *bags() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>> *>(VT_BAGS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>> *items_equiped() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>> *>(VT_ITEMS_EQUIPED);
  }
  const GWIPC::DialogsInfo *dialogs_info() const {
    return GetPointer<const GWIPC::DialogsInfo *>(VT_DIALOGS_INFO);
  }
  const flatbuffers::String *nav_mesh_file_path() const {
    return GetPointer<const flatbuffers::String *>(VT_NAV_MESH_FILE_PATH);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentItem>> *items() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentItem>> *>(VT_ITEMS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentGadget>> *gadgets() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentGadget>> *>(VT_GADGETS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Enemy>> *enemies() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Enemy>> *>(VT_ENEMIES);
  }
  const GWIPC::Bag *unclaimed_items() const {
    return GetPointer<const GWIPC::Bag *>(VT_UNCLAIMED_ITEMS);
  }
  const GWIPC::Bag *material_storage() const {
    return GetPointer<const GWIPC::Bag *>(VT_MATERIAL_STORAGE);
  }
  const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>> *storage() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>> *>(VT_STORAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           VerifyOffset(verifier, VT_INSTANCE) &&
           verifier.VerifyTable(instance()) &&
           VerifyOffset(verifier, VT_PARTY) &&
           verifier.VerifyTable(party()) &&
           VerifyField<int8_t>(verifier, VT_GAME_STATE, 1) &&
           VerifyOffset(verifier, VT_QUESTS) &&
           verifier.VerifyVector(quests()) &&
           verifier.VerifyVectorOfTables(quests()) &&
           VerifyOffset(verifier, VT_BAGS) &&
           verifier.VerifyVector(bags()) &&
           verifier.VerifyVectorOfTables(bags()) &&
           VerifyOffset(verifier, VT_ITEMS_EQUIPED) &&
           verifier.VerifyVector(items_equiped()) &&
           verifier.VerifyVectorOfTables(items_equiped()) &&
           VerifyOffset(verifier, VT_DIALOGS_INFO) &&
           verifier.VerifyTable(dialogs_info()) &&
           VerifyOffset(verifier, VT_NAV_MESH_FILE_PATH) &&
           verifier.VerifyString(nav_mesh_file_path()) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           VerifyOffset(verifier, VT_GADGETS) &&
           verifier.VerifyVector(gadgets()) &&
           verifier.VerifyVectorOfTables(gadgets()) &&
           VerifyOffset(verifier, VT_ENEMIES) &&
           verifier.VerifyVector(enemies()) &&
           verifier.VerifyVectorOfTables(enemies()) &&
           VerifyOffset(verifier, VT_UNCLAIMED_ITEMS) &&
           verifier.VerifyTable(unclaimed_items()) &&
           VerifyOffset(verifier, VT_MATERIAL_STORAGE) &&
           verifier.VerifyTable(material_storage()) &&
           VerifyOffset(verifier, VT_STORAGE) &&
           verifier.VerifyVector(storage()) &&
           verifier.VerifyVectorOfTables(storage()) &&
           verifier.EndTable();
  }
};

struct ClientDataBuilder {
  typedef ClientData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_character(flatbuffers::Offset<GWIPC::Character> character) {
    fbb_.AddOffset(ClientData::VT_CHARACTER, character);
  }
  void add_instance(flatbuffers::Offset<GWIPC::Instance> instance) {
    fbb_.AddOffset(ClientData::VT_INSTANCE, instance);
  }
  void add_party(flatbuffers::Offset<GWIPC::Party> party) {
    fbb_.AddOffset(ClientData::VT_PARTY, party);
  }
  void add_game_state(GWIPC::GameState game_state) {
    fbb_.AddElement<int8_t>(ClientData::VT_GAME_STATE, static_cast<int8_t>(game_state), 0);
  }
  void add_quests(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Quest>>> quests) {
    fbb_.AddOffset(ClientData::VT_QUESTS, quests);
  }
  void add_bags(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>>> bags) {
    fbb_.AddOffset(ClientData::VT_BAGS, bags);
  }
  void add_items_equiped(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>>> items_equiped) {
    fbb_.AddOffset(ClientData::VT_ITEMS_EQUIPED, items_equiped);
  }
  void add_dialogs_info(flatbuffers::Offset<GWIPC::DialogsInfo> dialogs_info) {
    fbb_.AddOffset(ClientData::VT_DIALOGS_INFO, dialogs_info);
  }
  void add_nav_mesh_file_path(flatbuffers::Offset<flatbuffers::String> nav_mesh_file_path) {
    fbb_.AddOffset(ClientData::VT_NAV_MESH_FILE_PATH, nav_mesh_file_path);
  }
  void add_items(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentItem>>> items) {
    fbb_.AddOffset(ClientData::VT_ITEMS, items);
  }
  void add_gadgets(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentGadget>>> gadgets) {
    fbb_.AddOffset(ClientData::VT_GADGETS, gadgets);
  }
  void add_enemies(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Enemy>>> enemies) {
    fbb_.AddOffset(ClientData::VT_ENEMIES, enemies);
  }
  void add_unclaimed_items(flatbuffers::Offset<GWIPC::Bag> unclaimed_items) {
    fbb_.AddOffset(ClientData::VT_UNCLAIMED_ITEMS, unclaimed_items);
  }
  void add_material_storage(flatbuffers::Offset<GWIPC::Bag> material_storage) {
    fbb_.AddOffset(ClientData::VT_MATERIAL_STORAGE, material_storage);
  }
  void add_storage(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>>> storage) {
    fbb_.AddOffset(ClientData::VT_STORAGE, storage);
  }
  explicit ClientDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ClientData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ClientData>(end);
    return o;
  }
};

inline flatbuffers::Offset<ClientData> CreateClientData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::Character> character = 0,
    flatbuffers::Offset<GWIPC::Instance> instance = 0,
    flatbuffers::Offset<GWIPC::Party> party = 0,
    GWIPC::GameState game_state = GWIPC::GameState_Unknown,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Quest>>> quests = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>>> bags = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Item>>> items_equiped = 0,
    flatbuffers::Offset<GWIPC::DialogsInfo> dialogs_info = 0,
    flatbuffers::Offset<flatbuffers::String> nav_mesh_file_path = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentItem>>> items = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::AgentGadget>>> gadgets = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Enemy>>> enemies = 0,
    flatbuffers::Offset<GWIPC::Bag> unclaimed_items = 0,
    flatbuffers::Offset<GWIPC::Bag> material_storage = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<GWIPC::Bag>>> storage = 0) {
  ClientDataBuilder builder_(_fbb);
  builder_.add_storage(storage);
  builder_.add_material_storage(material_storage);
  builder_.add_unclaimed_items(unclaimed_items);
  builder_.add_enemies(enemies);
  builder_.add_gadgets(gadgets);
  builder_.add_items(items);
  builder_.add_nav_mesh_file_path(nav_mesh_file_path);
  builder_.add_dialogs_info(dialogs_info);
  builder_.add_items_equiped(items_equiped);
  builder_.add_bags(bags);
  builder_.add_quests(quests);
  builder_.add_party(party);
  builder_.add_instance(instance);
  builder_.add_character(character);
  builder_.add_game_state(game_state);
  return builder_.Finish();
}

inline flatbuffers::Offset<ClientData> CreateClientDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<GWIPC::Character> character = 0,
    flatbuffers::Offset<GWIPC::Instance> instance = 0,
    flatbuffers::Offset<GWIPC::Party> party = 0,
    GWIPC::GameState game_state = GWIPC::GameState_Unknown,
    const std::vector<flatbuffers::Offset<GWIPC::Quest>> *quests = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::Bag>> *bags = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::Item>> *items_equiped = nullptr,
    flatbuffers::Offset<GWIPC::DialogsInfo> dialogs_info = 0,
    const char *nav_mesh_file_path = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::AgentItem>> *items = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::AgentGadget>> *gadgets = nullptr,
    const std::vector<flatbuffers::Offset<GWIPC::Enemy>> *enemies = nullptr,
    flatbuffers::Offset<GWIPC::Bag> unclaimed_items = 0,
    flatbuffers::Offset<GWIPC::Bag> material_storage = 0,
    const std::vector<flatbuffers::Offset<GWIPC::Bag>> *storage = nullptr) {
  auto quests__ = quests ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Quest>>(*quests) : 0;
  auto bags__ = bags ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Bag>>(*bags) : 0;
  auto items_equiped__ = items_equiped ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Item>>(*items_equiped) : 0;
  auto nav_mesh_file_path__ = nav_mesh_file_path ? _fbb.CreateString(nav_mesh_file_path) : 0;
  auto items__ = items ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::AgentItem>>(*items) : 0;
  auto gadgets__ = gadgets ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::AgentGadget>>(*gadgets) : 0;
  auto enemies__ = enemies ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Enemy>>(*enemies) : 0;
  auto storage__ = storage ? _fbb.CreateVector<flatbuffers::Offset<GWIPC::Bag>>(*storage) : 0;
  return GWIPC::CreateClientData(
      _fbb,
      character,
      instance,
      party,
      game_state,
      quests__,
      bags__,
      items_equiped__,
      dialogs_info,
      nav_mesh_file_path__,
      items__,
      gadgets__,
      enemies__,
      unclaimed_items,
      material_storage,
      storage__);
}

inline const GWIPC::ClientData *GetClientData(const void *buf) {
  return flatbuffers::GetRoot<GWIPC::ClientData>(buf);
}

inline const GWIPC::ClientData *GetSizePrefixedClientData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<GWIPC::ClientData>(buf);
}

inline bool VerifyClientDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GWIPC::ClientData>(nullptr);
}

inline bool VerifySizePrefixedClientDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GWIPC::ClientData>(nullptr);
}

inline void FinishClientDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<GWIPC::ClientData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedClientDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<GWIPC::ClientData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace GWIPC

#endif  // FLATBUFFERS_GENERATED_CLIENTDATA_GWIPC_H_
